# Comparrisions between graphs

In [16]:
import numpy as np
import plotly
import plotly.graph_objs as go
import plotly.plotly as py

def subplot_shared_xAxis(x_axis, data1, data2, file_name, plt_name1,plt_name2):
	trace0 = go.Scatter(x=x_axis, y=data1,
						name=plt_name1,
						mode="lines+markers")
	# mode can be 'markers', 'lines+markers', 'lines'

	trace1 = go.Scatter(x=x_axis, y=data2,
						name=plt_name2,
						mode="lines+markers",
						yaxis = "y2")

	mydata = [trace0, trace1]

	layout = go.Layout(
		yaxis=dict(
			domain=[0, 0.5]
		),
		yaxis2=dict(
			domain=[0.5, 1]
		),
	)


	fig = go.Figure(data=mydata, layout=layout)

	plotly.offline.plot(fig, filename=file_name)
    



fh = open("/home/chenidan/nucleusome/non_pos_vecs/non_loc_vecs")
segal_pos_indep_probs = np.load("/home/chenidan/nucleusome/segal_results/pos_indep_probs.npy")
counter = 0
line_num =1

for line in fh:
	if counter == line_num:
		vec = ((line.split('::'))[0].split(';'))
		loc_str = ((line.split('::'))[1].split(':'))[1]
		print ((line.split('::'))[1].split(':'))[0]
		seq_range= loc_str.split('-')
		seq_range= map(int, seq_range)
		vec = map(float, vec)
		subplot_shared_xAxis(range(seq_range[0], seq_range[1]), segal_pos_indep_probs, vec, "avrege_cmp.html", "nuc occ avg", "loc_indep_scores")
		print np.corrcoef(segal_pos_indep_probs[seq_range[0]-1:seq_range[1]],vec)
		break
	counter= counter + 1

1
[[ 1.         -0.60272869]
 [-0.60272869  1.        ]]


In [18]:
def cmp_loc_indep(v1, v2,inv):


	if inv:
		kaplan_pos_indep_probs = np.load("/home/chenidan/nucleusome/test graphs/pos_indep_kaplan/inv/pos_indep_probs.npy")
		dir = "/home/chenidan/nucleusome/test graphs/pos_indep_kaplan/inv/"
	else:
		kaplan_pos_indep_probs = np.load("/home/chenidan/nucleusome/test graphs/pos_indep_kaplan/non_inv/pos_indep_probs.npy")
		dir = "/home/chenidan/nucleusome/test graphs/pos_indep_kaplan/non_inv/"
	segal_pos_indep_probs = np.load("/home/chenidan/nucleusome/segal_results/pos_indep_probs.npy")
	subplot_shared_xAxis(range(v1,v2), kaplan_pos_indep_probs[v1:v2], segal_pos_indep_probs[v1:v2], dir+ "kaplan_vs_segal PL scores, window" +str([v1,v2])+".html", "kaplan","segal")
	print np.corrcoef(kaplan_pos_indep_probs[v1:v2],segal_pos_indep_probs[v1:v2])

cmp_loc_indep(0, 4000,1)

[[1.         0.75445495]
 [0.75445495 1.        ]]


In [9]:
def cmp_loc_indep(v1, v2,inv):


	if inv:
		kaplan_pos_indep_probs = np.load("/home/chenidan/nucleusome/test graphs/pos_indep_kaplan/inv/pos_indep_probs.npy")
		dir = "/home/chenidan/nucleusome/test graphs/pos_indep_kaplan/inv/"
	else:
		kaplan_pos_indep_probs = np.load("/home/chenidan/nucleusome/test graphs/pos_indep_kaplan/non_inv/pos_indep_probs.npy")
		dir = "/home/chenidan/nucleusome/test graphs/pos_indep_kaplan/non_inv/"
	segal_pos_indep_probs = np.load("/home/chenidan/nucleusome/segal_results/pos_indep_probs.npy")
	subplot_shared_xAxis(range(v1,v2), kaplan_pos_indep_probs[v1:v2], segal_pos_indep_probs[v1:v2], dir+ "kaplan_vs_segal PL scores, window" +str([v1,v2])+".html", "kaplan","segal")
	print np.corrcoef(kaplan_pos_indep_probs[v1:v2],segal_pos_indep_probs[v1:v2])

cmp_loc_indep(0, 4000,0)

[[ 1.        -0.6792361]
 [-0.6792361  1.       ]]


In [19]:
import pandas as pd

def cmp_loc_dep():
	kaplan_pos_dep_probs = np.load("/home/chenidan/nucleusome/test graphs/pos_dep_kaplan/pos_dep_probs.npy")
	segal_pos_indep_probs = np.load("/home/chenidan/nucleusome/segal_results/pos_indep_probs.npy")
	dir = "/home/chenidan/nucleusome/test graphs/pos_dep_kaplan/"

	segal_scores = pd.read_csv("/home/chenidan/nucleusome/segal_results/scores.tab", delimiter="\t")
	segal_scores = segal_scores._getitem_column("Raw Binding (log ratio)")

	segal_pos_dep_probs = segal_scores + segal_pos_indep_probs[0:len(segal_scores)]
	print np.corrcoef(kaplan_pos_dep_probs[0:len(segal_scores)], segal_pos_dep_probs[0:len(segal_scores)])

	subplot_shared_xAxis(range(0,len(segal_scores)), kaplan_pos_dep_probs[0:len(segal_scores)], segal_pos_dep_probs[0:len(segal_scores)], dir + "kaplan_vs_segal P_N scores, window" +str([0,len(segal_scores)])+".html", "kaplan","segal")

cmp_loc_dep()

[[1.         0.64679389]
 [0.64679389 1.        ]]


In [20]:
import pandas as pd
def cmp_scores(inv):
	if inv:
		kaplan_pos_indep_probs = np.load("/home/chenidan/nucleusome/test graphs/pos_indep_kaplan/inv/pos_indep_probs.npy")
	else:
		kaplan_pos_indep_probs = np.load("/home/chenidan/nucleusome/test graphs/pos_indep_kaplan/non_inv/pos_indep_probs.npy")
	dir = "/home/chenidan/nucleusome/test graphs/segal_results/segal_scores/"
	kaplan_scores = np.load("/home/chenidan/nucleusome/test graphs/pos_dep_kaplan/pos_dep_probs.npy") - kaplan_pos_indep_probs
	segal_scores = pd.read_csv("/home/chenidan/nucleusome/segal_results/scores.tab", delimiter="\t")
	segal_scores = segal_scores._getitem_column("Raw Binding (log ratio)")
	subplot_shared_xAxis(range(0, len(segal_scores)), segal_scores[0:len(segal_scores)], kaplan_scores[0:len(segal_scores)], dir + "kaplan_vs_segal_scores"+".html",
						 "segal_scores", "kaplan_scores")

	print np.corrcoef(segal_scores[0:len(segal_scores)], kaplan_scores[0:len(segal_scores)])
    
    
cmp_scores(0)
cmp_scores(1)

[[1.         0.03067603]
 [0.03067603 1.        ]]
[[ 1.        -0.0357242]
 [-0.0357242  1.       ]]
